name: Dart
on:
  pull_request:

concurrency:
  group: dart-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dart:
    name: Dart
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Login to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: Install dart
        uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1
        with:
          sdk: 3.11
      - name: Get dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed --line-length 120 .
      - name: Lint code
        run: dart analyze --fatal-infos .
      - name: Run tests
        run: |
          ./scripts/build-containers.sh
          dart test
