name: Generate
on:
  pull_request:

concurrency:
  group: generate-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Submodules
        run: git submodule update --init --depth 0
      - name: Install dart
        uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
        with:
          sdk: 3.11
      - name: Install php
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: "8.1"
          tools: composer
      # Use https://github.com/kislyuk/yq
      - name: Install yq
        run: pip install yq --break-system-packages
      - name: Generate
        run: |
          dart pub get
          ./scripts/generate.sh
          git --no-pager diff --exit-code
