name: 'Update test presets'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
        with:
          sdk: 3.11
      - name: Update presets
        run: |
          dart pub get
          ./scripts/generate-test-presets.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          commit-message: "chore(nextcloud_test_presets): Update presets"
          signoff: true
          branch: chore/nextcloud_test_presets/update-presets
          delete-branch: true
          title: "chore(nextcloud_test_presets): Update presets"
          body: "`git checkout chore/nextcloud_test_presets/update-presets && git commit --amend -s --no-edit && git push -f` locally to trigger the CI."
